### post
POST http://developers.gictsystems.com/api/dummy/submit/ HTTP/1.1
Content-Type: application/json

{
    "fullnames": "first mid last",
    "email": "flast@email.com",
    "phone": "123456789",
    "address": "first addr line, second address line"
}

### get
GET http://developers.gictsystems.com/api/dummy/items/ HTTP/1.1
Authorization: Bearer ALDJAK23423JKSLAJAF23423J23SAD3